//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUENTAS
    {
        public CUENTAS()
        {
            this.MOVIMIENTOS = new HashSet<MOVIMIENTOS>();
        }
    
        public decimal CUE_NUMERO { get; set; }
        public System.DateTime CUE_FECHA_APE { get; set; }
        public string CUE_TIPO { get; set; }
        public decimal CUE_SALDO_DISP { get; set; }
        public decimal CUE_SALDO_TOT { get; set; }
        public decimal CUE_SOBRECUPO { get; set; }
        public string CUE_ESTADO { get; set; }
        public decimal CLI_ID { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual ICollection<MOVIMIENTOS> MOVIMIENTOS { get; set; }
    }
}
