//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAMETROS
    {
        public int PAR_ID { get; set; }
        public string PAR_NOM { get; set; }
        public decimal PAR_VALOR { get; set; }
    }
}
