//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public string USU_LOGIN { get; set; }
        public string USU_PWD { get; set; }
        public string USU_TIPO { get; set; }
        public decimal CLI_ID { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
    }
}
